dist: trusty
sudo: required
language: generic

services:
  - docker

env:
  matrix:
  - COQ_IMAGE="ocaml/opam2:4.05"

# As described on https://bors.tech/documentation/getting-started/ we need a
# `staging` and a `trying` branch, both of which need to be CI-enabled.
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Uncomment this to enable building pull requests.
    # - master
    # (Left commented out until we find that it would be useful to enable)
    # We want to have CI for all master branches that target specific coq versions.
    - /master-.*/

install: |
  # Run the COQ container and display build metadata
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/Mtac2 -w /home/coq/Mtac2 ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    opam config list
    opam repo list
    opam list
    opam repo add coq-released https://coq.inria.fr/opam/released
    opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
    opam repo list
    sudo apt install -y m4
    opam install -y coq.dev
    coqc --version
    opam pin --ignore-constraints-on=coq add coq-unicoq https://github.com/unicoq/unicoq.git#master
    opam pin
    opam list
    "
script:
- echo -e "${ANSI_YELLOW}Building Mtac2...${ANSI_RESET}" && echo -en 'travis_fold:start:Mtac2.build\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R opam:opam /home/coq/Mtac2
    ./configure.sh
    make
    make test
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:Mtac2.build\\r'

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/2fc197f36f7c587c0f59
        - https://mattermost.mpi-sws.org/hooks/tyg3f3w7gpdaprgo1krzc94j7o
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
